version: '3.7'
services:
    app:
        build: .
        depends_on: 
            - database
        image: node:16
        working_dir: /app
        volumes:
            - ./app:/app
        command: npm start
        ports:
            - "3000:3000"
        links:
            - database

    database:
        image: mysql:5.7
        ports:
            - "3307:3036"
        environment:
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_DATABASE: sch_learecords
            MYSQL_USER: MainUser
            MYSQL_PASSWORD: 123456
        volumes:
            - ./init:/docker-entrypoint-initdb.d
            - "./.mysql-data/db:/var/lib/mysql"
